services:
    dreamlex_google_spreadsheet:
        class: Dreamlex\Bundle\GoogleSpreadsheetBundle\Spreadsheet\GoogleSpreadsheet
        arguments:
            - "%kernel.root_dir%"
            - "%dreamlex_google_spreadsheet.app_name%"
            - "%dreamlex_google_spreadsheet.scope%"
            - ~
        lazy:  true